#!/usr/bin/env python3
"""Rebuild the original, ONE-SIDED K6ARK outline; no mirror or scaling.

  uv run --no-project --with shapely python generate_native_profile.py \
    ~/Downloads/K6ARK_Wire_Winder.stl

The generated SCAD is standalone. Normalization subtracts 62.5 mm from X.
Tiny numerical holes are removed; true openings remain in the embedded data.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import struct

from shapely import affinity, union_all
from shapely.geometry import Polygon
from shapely.geometry.polygon import orient

SOURCE_SHA256 = "d023e8ecb8b5e7718d9f2c8431a90b2c823550a700396df8e0421103dbf5ad0d"
SOURCE_URL = "https://www.printables.com/model/383037-k6ark-wire-antenna-winder-ul-wireframe-model"


def load_silhouette(path):
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"Expected source {SOURCE_SHA256}, got {digest}")
    count = struct.unpack_from("<I", data, 80)[0]
    if len(data) != 84 + count * 50:
        raise ValueError("Invalid binary STL length")
    projected = []
    for i in range(count):
        triangle = struct.unpack_from("<12f", data, 84 + i * 50)
        polygon = Polygon([triangle[j:j + 2] for j in (3, 6, 9)])
        if polygon.area > 1e-10:
            projected.append(polygon)
    silhouette = union_all(projected)
    if silhouette.geom_type != "Polygon" or not silhouette.is_valid:
        raise ValueError("Source does not project to one valid polygon")
    return silhouette


def canonical(ring, ccw):
    points = [tuple(round(v, 6) for v in p) for p in list(ring.coords)[:-1]]
    if Polygon(points).exterior.is_ccw != ccw:
        points.reverse()
    start = min(range(len(points)), key=lambda i: points[i])
    return points[start:] + points[:start]


def generate(source, output):
    source_outline = load_silhouette(source)
    normalized = affinity.translate(source_outline, xoff=-62.5)
    holes = [r for r in normalized.interiors if Polygon(r).area >= 1e-8]
    cleaned = orient(Polygon(normalized.exterior, holes).simplify(1e-5, preserve_topology=True))
    rings = [canonical(cleaned.exterior, True)]
    rings += [canonical(r, False) for r in sorted(cleaned.interiors, key=lambda r: Polygon(r).bounds)]
    final = Polygon(rings[0], rings[1:])
    assert final.is_valid
    error = final.exterior.hausdorff_distance(normalized.exterior)
    assert error < 0.000011
    small = [i for i, r in enumerate(rings) if i and Polygon(r).area < 10]
    text = [
        "// Generated by generate_native_profile.py; preserve attribution in NOTICE.md.",
        "// K6ARK UL Wireframe Winder by Adam Kimmerly (K6ARK).",
        f"// {SOURCE_URL}", f"// Source SHA256: {SOURCE_SHA256}",
        "// ORIGINAL one-sided outline: X=source_X-62.5; Y=source_Y. No mirroring/scaling.",
        "// Native bounds 140 x 54.043564 mm. Source thickness 5 mm.",
        "function native_points() = [",
    ]
    for i, ring in enumerate(rings):
        text.append(f"    // {'Exterior' if i == 0 else f'Native opening {i}'}")
        text += ["    [" + ", ".join(f"{v:.6f}".rstrip("0").rstrip(".") for v in p) + "]," for p in ring]
    text += ["];", "function native_paths(fill_small_windows=false) =", "    let(paths = ["]
    offset = 0
    for ring in rings:
        text.append("        [" + ",".join(str(i) for i in range(offset, offset + len(ring))) + "],")
        offset += len(ring)
    text += ["    ], small = " + str(small) + ")", "    [for(i=[0:len(paths)-1]) if(!fill_small_windows || len(search(i,small))==0) paths[i]];", "", "module native_frame_2d(fill_small_windows=false) {", "    polygon(points=native_points(), paths=native_paths(fill_small_windows), convexity=20);", "}", ""]
    output.write_text("\n".join(text))
    report = {"source_sha256": SOURCE_SHA256, "source_url": SOURCE_URL,
              "transform": "X=source_X-62.5; Y=source_Y; original one-sided profile",
              "bounds_xy_mm": list(final.bounds), "native_openings": len(rings)-1,
              "optional_filled_small_window_ids": small,
              "outer_boundary_max_deviation_mm": error,
              "area_symmetric_difference_mm2": final.symmetric_difference(normalized).area,
              "native_projected_area_mm2": final.area}
    output.with_suffix(".json").write_text(json.dumps(report, indent=2)+"\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("native_profile.scad"))
    args = parser.parse_args()
    generate(args.source, args.output)
